---
name: Molecule Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
defaults:
  run:
    working-directory: 'freeipa_backup'
jobs:
  call-workflow-passing-data:
    uses: infra-monkey/reuseable_workflows/.github/workflows/ansible_role_molecule.yml@main
    with:
      role_name: 'freeipa_backup'
